draw_set_font(TheHelperfont);

if (atk1 or atk2 or atk3) {
	draw_text(0, 0, "ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL");
	draw_text(0, 778, "ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL || ATTACK INCOMING!! SHOOT TO CANCEL");
}

draw_set_font(GUIfont);

draw_text(64, 64, "Boss Health: " + string(global.life));